---
# This playbook deploys a simple Tomcat 7 cluster behind an HAProxy. 

- hosts: tomcat-servers 
  remote_user: root

  roles:
    - selinux
    - tomcat
    - webapp

- hosts: lbservers
  remote_user: root

  roles:
    - selinux
    - haproxy
